- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: /home/ubuntu/

- name: Create service configuration
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-service.yaml"
  args:
    chdir: /home/ubuntu/
